openapi: 3.0.3
info:
  title: Ynova Gestão - Contracts API
  version: 1.0.0
paths:
  /contracts:
    get:
      summary: List contracts with filters
      parameters:
        - in: query
          name: page
          schema: { type: integer, minimum: 1, default: 1 }
        - in: query
          name: pageSize
          schema: { type: integer, minimum: 1, maximum: 100, default: 10 }
        - in: query
          name: search
          schema: { type: string }
        - in: query
          name: cnpj
          schema: { type: string }
        - in: query
          name: status
          schema: { type: string, enum: [Ativo, "Em análise", Inativo] }
        - in: query
          name: startDate
          schema: { type: string, pattern: '^[0-9]{4}-[0-9]{2}$' }
        - in: query
          name: endDate
          schema: { type: string, pattern: '^[0-9]{4}-[0-9]{2}$' }
      responses:
        '200':
          description: Contract list
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Contract' }
components:
  schemas:
    Contract:
      type: object
      properties:
        id: { type: string }
        contract_code: { type: string }
        client_id: { type: string }
        client_name: { type: string }
        cnpj: { type: string }
        segment: { type: string }
        contact_responsible: { type: string }
        contracted_volume_mwh: { type: string }
        status: { type: string, enum: [Ativo, "Em análise", Inativo] }
        energy_source: { type: string }
        contracted_modality: { type: string }
        start_date: { type: string, format: date-time }
        end_date: { type: string, format: date-time }
        billing_cycle: { type: string }
        upper_limit_percent: { type: string, nullable: true }
        lower_limit_percent: { type: string, nullable: true }
        flexibility_percent: { type: string, nullable: true }
        average_price_mwh: { type: string }
        spot_price_ref_mwh: { type: string }
        compliance_consumption: { type: string }
        compliance_nf: { type: string }
        compliance_invoice: { type: string }
        compliance_charges: { type: string }
        compliance_overall: { type: string }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
